# 配置Tomcat端口号
server:
  port: 9997
# 配置Spring Boot项目名
spring:
  application:
    name: xmall-admin
# 配置Dubbo信息
  dubbo:
    application:
      name: xmall-admin
    protocol:
      name: dubbo
      port: 20880
      serialization: java
    registry:
      address: zookeeper://localhost:2181
    scan: com.zhuxintao.xmall
# 配置MVC视图解析器的前后缀信息
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
# 配置JDBC数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peppa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: java
# 配置JPA相关信息
  jpa:
    show-sql: true
    open-in-view: true
   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    